In [1]:
%load_ext autoreload
%autoreload 2
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader

import numpy as np
import math

In [2]:
# input = torch.randint(high=5, size=(1, 3)) # (batch, seq_len)
# # print(f'input :\n {input}')

# range_seq = torch.arange(input.shape[1])
# # print(f'range_seq :\n {range_seq}')

# d_model = 10
# in_embed = InputEmbedding(d_model=d_model, vocab_size=20)
# pe = PositionalEncoding(d_model=d_model, seq_len=input.shape[1], dropout=.5)

# embeds = in_embed(input)
# # print(f'embeds : \n {embeds}\n')

# pe_embededs = pe(embeds)
# # print(f'pe_embededs : \n {pe_embededs}\n')

# norm = LayerNormalization()
# norm_outs = norm(pe_embededs)


# ff = FeedForward(d_model=d_model, d_ff=2024, dropuout=.3)
# ff_outs = ff(norm_outs)
# # print(ff_outs.shape)


# # att = MultiHeadAttention(d_model=d_model, num_heads=2, dropout=.3)
# # att_outs = att(ff_outs, ff_outs, ff_outs, mask=None)
# # att_outs


# encoder = Encoder(num_encoders=2, d_model=d_model, d_ff=100, num_heads=5, dropout=.3)
# encoder_outs = encoder(ff_outs)

# proj = ProjectionLayer(d_model=d_model, vocab_size=20)
# proj_outs = proj(encoder_outs)
# # proj_outs.shape


# # input = torch.randint(high=5, size=(1, 3)) # (batch, seq_len)
# # gpt = GPT(d_model=d_model, vocab_size=20, seq_len=30, num_encoders=5, num_heads=5, d_ff=100, pos_drop=.3, encoder_drop=.3)
# # gpt_outs = gpt(input)

In [3]:
# from model import GPT

# input = torch.randint(high=5, size=(1, 30)) # (batch, seq_len)
# gpt = GPT(d_model=10, vocab_size=20, seq_len=30, num_encoders=5, num_heads=5, d_ff=100, pos_drop=.3, encoder_drop=.3)
# gpt_outs = gpt(input)
# gpt_outs.shape

In [4]:
from transformers import GPT2Tokenizer
tokenizer_name = 'gpt2'
tokenizer = GPT2Tokenizer.from_pretrained(tokenizer_name)

text = 'Hi, how are you      ?      '
tokens = tokenizer.encode(text)
print(tokens)
print(tokenizer.decode(tokens))

[17250, 11, 703, 389, 345, 220, 220, 220, 220, 220, 5633, 220, 220, 220, 220, 220, 220]
Hi, how are you     ?      


In [5]:
# !curl -O https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

datase_text_file_path = './data/input.txt'
with open(datase_text_file_path, 'r', encoding='utf-8') as f:
    data = f.read()

print(data[: 80])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.


In [6]:
n = len(data)
train_data = data[:int(n*.9)]
val_data = data[int(n*.9):]

In [7]:
len(train_data), len(val_data)

(1003854, 111540)

In [8]:
train_ids = tokenizer.encode(train_data)
val_ids = tokenizer.encode(val_data)
print(f"train has {len(train_ids):,} tokens")
print(f"val has {len(val_ids):,} tokens")

# export to bin files
import numpy as np
import os
train_ids = np.array(train_ids, dtype=np.int32)
val_ids = np.array(val_ids, dtype=np.int32)
train_ids.tofile(os.path.join(os.path.dirname('./data/'), 'train.bin'))
val_ids.tofile(os.path.join(os.path.dirname('./data/'), 'val.bin'))

Token indices sequence length is longer than the specified maximum sequence length for this model (301966 > 1024). Running this sequence through the model will result in indexing errors


train has 301,966 tokens
val has 36,059 tokens


In [47]:
class GPTDataset(Dataset):
    def __init__(self, bin_file_path, seq_len):
        self.seq_len = seq_len
        # Load tokens from the file
        with open(bin_file_path, 'rb') as f:
            self.tokens = np.fromfile(f, dtype=np.int32)

    def __len__(self):
        return int(len(self.tokens) / self.seq_len)

    def __getitem__(self, idx):
        
        if idx + self.seq_len >= len(self.tokens):
            idx = len(self.tokens) - self.seq_len -1

        x = self.tokens[idx: idx + self.seq_len]
        y = self.tokens[idx + 1: idx + self.seq_len + 1]

        return torch.tensor(x, dtype=torch.long), torch.tensor(y, dtype=torch.long)


In [48]:
from configs import get_gpt_configs
model_configs = get_gpt_configs()

train_bin_file_path = './data/train.bin'
val_bin_file_path = './data/val.bin'

train_ds = GPTDataset(train_bin_file_path, model_configs['seq_len'])
val_ds = GPTDataset(val_bin_file_path, model_configs['seq_len'])

batch_size = 32

train_dl = DataLoader(train_ds, batch_size=batch_size)
val_dl = DataLoader(val_ds, batch_size=batch_size)

input_tokens, output_tokens = next(iter(val_dl))
input_tokens.shape, output_tokens.shape

(torch.Size([32, 5]), torch.Size([32, 5]))

In [77]:
from model import GPT

gpt = GPT(**model_configs)
gpt_outs = gpt(input_tokens)
gpt_outs.shape

attention_scores: 
 tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4708, 0.5292, 0.0000, 0.0000, 0.0000],
        [0.2606, 0.3317, 0.4078, 0.0000, 0.0000],
        [0.2873, 0.2169, 0.1225, 0.3733, 0.0000],
        [0.2516, 0.1822, 0.1162, 0.2894, 0.1606]], grad_fn=<SelectBackward0>) 
values: 
 tensor([[ 0.1130, -0.1978,  0.7137],
        [ 0.6939, -0.2477, -0.8871],
        [ 0.0853, -0.7271, -0.1763],
        [ 0.3369,  0.9905, -0.3579],
        [-0.2748, -0.1715,  0.1362]], grad_fn=<SelectBackward0>) 
res before drop : 
 tensor([[ 0.1130, -0.1978,  0.7137],
        [ 0.4205, -0.2242, -0.1335],
        [ 0.2944, -0.4302, -0.1801],
        [ 0.3192,  0.1702, -0.1426],
        [ 0.2181,  0.0797, -0.0842]], grad_fn=<SelectBackward0>) 
res after drop : 
 tensor([[ 0.1614, -0.2825,  1.0195],
        [ 0.6006, -0.3203, -0.1907],
        [ 0.3785, -0.5410, -0.5230],
        [ 0.2260,  0.4471,  0.1020],
        [ 0.3605,  0.2740, -0.1223]], grad_fn=<SelectBackward0>) 


torch.Size([32, 5, 50257])

In [ ]:
# from engine import train
# from model import GPT

# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# model = GPT(**model_configs)

# lr = 1e-5
# epochs = 3
# project_name = 'GPT'
# experiment_name = f'{model.__class__.__name__}, lr:{lr}'

# optimizer = torch.optim.Adam(params=model.parameters(), lr=lr)
# loss_fn = nn.CrossEntropyLoss()

# # configs to save for wandb
# hp_configs = {
#     'model':model.__class__.__name__,
#     'lr':lr,
#     'epochs':epochs,
#     'device':device
# }

# results = train(model=model,
#                 train_dl=train_dl,
#                 val_dl=val_dl,
#                 loss_fn=loss_fn,
#                 optimizer=optimizer,
#                 epochs=epochs,
#                 device=device,
#                 save_wandb=False,
#                 project_name=project_name,
#                 experiment_name=experiment_name,
#                 hyper_param_config=hp_configs)